/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DashboardProfileRouteImport } from './routes/dashboard.profile'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard.settings'
import { Route as DashboardSuggestionsRouteImport } from './routes/dashboard.suggestions'
import { Route as DashboardResumeIndexRouteImport } from './routes/dashboard.resume.index'
import { Route as DashboardResumeAnalysisRouteImport } from './routes/dashboard.resume.analysis'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProfileRoute = DashboardProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSuggestionsRoute = DashboardSuggestionsRouteImport.update({
  id: '/suggestions',
  path: '/suggestions',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardResumeIndexRoute = DashboardResumeIndexRouteImport.update({
  id: '/resume/',
  path: '/resume/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardResumeAnalysisRoute = DashboardResumeAnalysisRouteImport.update({
  id: '/resume/analysis',
  path: '/resume/analysis',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/suggestions': typeof DashboardSuggestionsRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/resume/analysis': typeof DashboardResumeAnalysisRoute
  '/dashboard/resume/': typeof DashboardResumeIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/suggestions': typeof DashboardSuggestionsRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/resume/analysis': typeof DashboardResumeAnalysisRoute
  '/dashboard/resume': typeof DashboardResumeIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/suggestions': typeof DashboardSuggestionsRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/resume/analysis': typeof DashboardResumeAnalysisRoute
  '/dashboard/resume/': typeof DashboardResumeIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/signup'
    | '/dashboard/profile'
    | '/dashboard/settings'
    | '/dashboard/suggestions'
    | '/dashboard/'
    | '/dashboard/resume/analysis'
    | '/dashboard/resume/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/dashboard/profile'
    | '/dashboard/settings'
    | '/dashboard/suggestions'
    | '/dashboard'
    | '/dashboard/resume/analysis'
    | '/dashboard/resume'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/signup'
    | '/dashboard/profile'
    | '/dashboard/settings'
    | '/dashboard/suggestions'
    | '/dashboard/'
    | '/dashboard/resume/analysis'
    | '/dashboard/resume/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/profile': {
      id: '/dashboard/profile'
      path: '/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof DashboardProfileRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/suggestions': {
      id: '/dashboard/suggestions'
      path: '/suggestions'
      fullPath: '/dashboard/suggestions'
      preLoaderRoute: typeof DashboardSuggestionsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/resume/': {
      id: '/dashboard/resume/'
      path: '/resume'
      fullPath: '/dashboard/resume/'
      preLoaderRoute: typeof DashboardResumeIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/resume/analysis': {
      id: '/dashboard/resume/analysis'
      path: '/resume/analysis'
      fullPath: '/dashboard/resume/analysis'
      preLoaderRoute: typeof DashboardResumeAnalysisRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardProfileRoute: typeof DashboardProfileRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardSuggestionsRoute: typeof DashboardSuggestionsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardResumeAnalysisRoute: typeof DashboardResumeAnalysisRoute
  DashboardResumeIndexRoute: typeof DashboardResumeIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardProfileRoute: DashboardProfileRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardSuggestionsRoute: DashboardSuggestionsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardResumeAnalysisRoute: DashboardResumeAnalysisRoute,
  DashboardResumeIndexRoute: DashboardResumeIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
